
export default {
    SV_SENSOR_DATA: 'SV_SENSOR_DATA',
    SV_CONTROL_DATA: 'SV_CONTROL_DATA',
    SV_ALARM_STATE_DATA: 'SV_ALARM_STATE_DATA',
    SV_NEW_FRAME: 'SV_NEW_FRAME',
    SV_ALL_VALUES: 'SV_ALL_VALUES'
};
